/**
 * Available texture to 2 letter ISO-3166-1 country codes
 *
 */
const FLAGS_CODE_TO_ISO = {
  '1': 'SY',
  '2': 'TH',
  '3': 'TM',
  '4': 'TN',
  '5': 'TR',
  '6': 'TT',
  '7': 'TW',
  '8': 'TZ',
  '9': 'UA',
  '10': 'UN',
  '11': 'US',
  '12': 'UY',
  '13': 'UZ',
  '14': 'VE',
  '15': 'VN',
  '16': 'PR',
  '17': 'PT',
  '18': 'PY',
  '19': 'QA',
  '20': 'RAINBOW',
  '21': 'RO',
  '22': 'RS',
  '23': 'RU',
  '24': 'SA',
  '25': 'SE',
  '26': 'SG',
  '27': 'SI',
  '28': 'SK',
  '29': 'SM',
  '30': 'MK',
  '31': 'MO',
  '32': 'MT',
  '33': 'MX',
  '34': 'MY',
  '35': 'NG',
  '36': 'NL',
  '37': 'NO',
  '38': 'NP',
  '39': 'NZ',
  '40': 'OM',
  '41': 'PA',
  '42': 'PE',
  '43': 'JP',
  '44': 'KP',
  '45': 'KR',
  '46': 'KW',
  '47': 'KZ',
  '48': 'LB',
  '49': 'LI',
  '50': 'LK',
  '51': 'LT',
  '52': 'LU',
  '53': 'LV',
  '54': 'HN',
  '55': 'HR',
  '56': 'HU',
  '57': 'ID',
  '58': 'IE',
  '59': 'IL',
  '60': 'IM',
  '61': 'IMPERIAL',
  '62': 'IN',
  '63': 'IQ',
  '64': 'DE',
  '65': 'DK',
  '66': 'DO',
  '67': 'DZ',
  '68': 'EC',
  '69': 'EE',
  '70': 'EG',
  '71': 'ES',
  '72': 'EU',
  '73': 'BH',
  '74': 'BO',
  '75': 'BR',
  '76': 'BT',
  '77': 'BY',
  '78': 'CA',
  '79': 'CH',
  '80': 'AD',
  '81': 'AE',
  '82': 'AL',
  '83': 'AM',
  '84': 'CL',
  '85': 'AQ',
  '86': 'CN',
  '87': 'AR',
  '88': 'FI',
  '89': 'CO',
  '90': 'AT',
  '91': 'IR',
  '92': 'FR',
  '93': 'COMMUNIST',
  '94': 'AU',
  '95': 'LY',
  '96': 'IS',
  '97': 'GB',
  '98': 'Antifa',
  '99': 'AZ',
  '100': 'MA',
  '101': 'IT',
  '102': 'GE',
  '103': 'CR',
  '104': 'BA',
  '105': 'PH',
  '106': 'MC',
  '107': 'JM',
  '108': 'GR',
  '109': 'CU',
  '110': 'BD',
  '111': 'SO',
  '112': 'PK',
  '113': 'MD',
  '114': 'JO',
  '115': 'GT',
  '116': 'CY',
  '117': 'BE',
  '118': 'ZA',
  '119': 'SV',
  '120': 'PL',
  '121': 'ME',
  '122': 'JOLLY',
  '123': 'HK',
  '124': 'CZ',
  '125': 'BG',
  '126': 'AC',
  '127': 'AF',
  '128': 'AG',
  '129': 'AI',
  '130': 'AO',
  '131': 'AS',
  '132': 'AW',
  '133': 'AX',
  '134': 'BB',
  '135': 'BF',
  '136': 'BI',
  '137': 'BJ',
  '138': 'BL',
  '139': 'BM',
  '140': 'BN',
  '141': 'BS',
  '142': 'BV',
  '143': 'BW',
  '144': 'BZ',
  '145': 'CC',
  '146': 'CD',
  '147': 'CF',
  '148': 'CG',
  '149': 'CI',
  '150': 'CK',
  '151': 'CM',
  '152': 'CP',
  '153': 'CV',
  '154': 'CW',
  '155': 'CX',
  '156': 'DG',
  '157': 'DJ',
  '158': 'DM',
  '159': 'EA',
  '160': 'EH',
  '161': 'ER',
  '162': 'ET',
  '163': 'FJ',
  '164': 'FK',
  '165': 'FM',
  '166': 'FO',
  '167': 'GA',
  '168': 'GD',
  '169': 'GF',
  '170': 'GG',
  '171': 'GH',
  '172': 'GI',
  '173': 'GL',
  '174': 'GM',
  '175': 'GN',
  '176': 'GP',
  '177': 'GQ',
  '178': 'GS',
  '179': 'GU',
  '180': 'GW',
  '181': 'GY',
  '182': 'HM',
  '183': 'HT',
  '184': 'IC',
  '185': 'IO',
  '186': 'JE',
  '187': 'KE',
  '188': 'KG',
  '189': 'KH',
  '190': 'KI',
  '191': 'KM',
  '192': 'KN',
  '193': 'KO',
  '194': 'KY',
  '195': 'LA',
  '196': 'LC',
  '197': 'LR',
  '198': 'LS',
  '199': 'MF',
  '200': 'MG',
  '201': 'MH',
  '202': 'ML',
  '203': 'MM',
  '204': 'MN',
  '205': 'MP',
  '206': 'MQ',
  '207': 'MR',
  '208': 'MS',
  '209': 'MU',
  '210': 'MV',
  '211': 'MW',
  '212': 'MZ',
  '213': 'NA',
  '214': 'NC',
  '215': 'NE',
  '216': 'NF',
  '217': 'NI',
  '218': 'NR',
  '219': 'NU',
  '220': 'PF',
  '221': 'PG',
  '222': 'PM',
  '223': 'PN',
  '224': 'PS',
  '225': 'PW',
  '226': 'RE',
  '227': 'RW',
  '228': 'SB',
  '229': 'SC',
  '230': 'SD',
  '231': 'SH',
  '232': 'SJ',
  '233': 'SL',
  '234': 'SN',
  '235': 'SR',
  '236': 'SS',
  '237': 'ST',
  '238': 'SX',
  '239': 'SZ',
  '240': 'TA',
  '241': 'TC',
  '242': 'TD',
  '243': 'TF',
  '244': 'TG',
  '245': 'TJ',
  '246': 'TK',
  '247': 'TL',
  '248': 'TO',
  '249': 'TV',
  '250': 'UG',
  '251': 'UM',
  '252': 'VA',
  '253': 'VC',
  '254': 'VG',
  '255': 'VI',
  '256': 'VU',
  '257': 'WF',
  '258': 'WS',
  '259': 'YE',
  '260': 'YT',
  '261': 'ZM',
  '262': 'ZW',
  '263': 'ENG',
  '264': 'SCT',
  '265': 'WLS',
  '266': 'RUI',
};

const FLAGS_ISO_TO_CODE = Object.assign(
  {},
  ...Object.entries(FLAGS_CODE_TO_ISO).map(([numCode, charCode]) => ({ [charCode]: ~~numCode }))
);

/**
 * Country by ISO 3166-2
 *
 */
const COUNTRY_NAMES = {
  AL: 'Albania',
  DZ: 'Algeria',
  AD: 'Andorra',
  AQ: 'Antarctica',
  AR: 'Argentina',
  AM: 'Armenia',
  AU: 'Australia',
  AT: 'Austria',
  AZ: 'Azerbaijan',
  BH: 'Bahrain',
  BD: 'Bangladesh',
  BY: 'Belarus',
  BE: 'Belgium',
  BT: 'Bhutan',
  BO: 'Bolivia',
  BA: 'Bosnia and Herzegovina',
  BR: 'Brazil',
  BG: 'Bulgaria',
  CA: 'Canada',
  CL: 'Chile',
  CN: 'China',
  CO: 'Colombia',
  COMMUNIST: 'Communist',
  Antifa: 'Antifa',
  CR: 'CostaRica',
  HR: 'Croatia',
  CU: 'Cuba',
  CY: 'Cyprus',
  CZ: 'Czech Republic',
  DK: 'Denmark',
  DO: 'Dominican Republic',
  KP: 'DPRK',
  EC: 'Ecuador',
  EG: 'Egypt',
  SV: 'ElSalvador',
  EE: 'Estonia',
  EU: 'European Union',
  FI: 'Finland',
  FR: 'France',
  GE: 'Georgia',
  DE: 'Germany',
  GR: 'Greece',
  GT: 'Guatemala',
  HN: 'Honduras',
  HK: 'HongKong',
  HU: 'Hungary',
  IS: 'Iceland',
  IMPERIAL: 'Imperial Japan',
  IN: 'India',
  ID: 'Indonesia',
  IR: 'Iran',
  IQ: 'Iraq',
  IE: 'Ireland',
  IM: 'Isle of Man',
  IL: 'Israel',
  IT: 'Italy',
  JM: 'Jamaica',
  JP: 'Japan',
  JOLLY: 'Jolly Rogers',
  JO: 'Jordan',
  KZ: 'Kazakhstan',
  KW: 'Kuwait',
  LV: 'Latvia',
  LB: 'Lebanon',
  LY: 'Libyan Arab Jamahiriya',
  LI: 'Liechtenstein',
  LT: 'Lithuania',
  LU: 'Luxembourg',
  MO: 'Macao',
  MK: 'Macedonia',
  MY: 'Malaysia',
  MT: 'Malta',
  MX: 'Mexico',
  MD: 'Moldova',
  MC: 'Monaco',
  ME: 'Montenegro',
  MA: 'Morocco',
  NP: 'Nepal',
  NL: 'Netherlands',
  NZ: 'New Zealand',
  NG: 'Nigeria',
  NO: 'Norway',
  OM: 'Oman',
  PK: 'Pakistan',
  PA: 'Panama',
  PY: 'Paraguay',
  PE: 'Peru',
  PH: 'Philippines',
  PL: 'Poland',
  PT: 'Portugal',
  PR: 'PuertoRico',
  QA: 'Qatar',
  RAINBOW: 'Rainbow',
  RO: 'Romania',
  RU: 'Russian Federation',
  SM: 'SanMarino',
  SA: 'Saudi Arabia',
  RS: 'Serbia',
  SG: 'Singapore',
  SK: 'Slovakia',
  SI: 'Slovenia',
  SO: 'Somalia',
  ZA: 'South Africa',
  KR: 'South Korea',
  ES: 'Spain',
  LK: 'Sri Lanka',
  SE: 'Sweden',
  CH: 'Switzerland',
  SY: 'Syrian Arab Republic',
  TW: 'Taiwan',
  TZ: 'Tanzania',
  TH: 'Thailand',
  TT: 'Trinidad and Tobago',
  TN: 'Tunisia',
  TR: 'Turkey',
  TM: 'Turkmenistan',
  UA: 'Ukraine',
  AE: 'United Arab Emirates',
  GB: 'United Kingdom',
  UN: 'United Nations',
  US: 'United States',
  UY: 'Uruguay',
  UZ: 'Uzbekistan',
  VE: 'Venezuela',
  VN: 'Vietnam',
  AC:	'Ascension Island',
  AF:	'Afghanistan',
  AG:	'Antigua & Barbuda',
  AI:	'Anguilla',
  AO:	'Angola',
  AS:	'American Samoa',
  AW:	'Aruba',
  AX:	'Åland Islands',
  BB:	'Barbados',
  BF:	'Burkina Faso',
  BI:	'Burundi',
  BJ:	'Benin',
  BL:	'St. Barthélemy',
  BM:	'Bermuda',
  BN:	'Brunei',
  BS:	'Bahamas',
  BV:	'Bouvet Island',
  BW:	'Botswana',
  BZ:	'Belize',
  CC:	'Cocos (Keeling) Islands',
  CD:	'Democratic Republic of the Congo',
  CF:	'Central African Republic',
  CG:	'Republic of the Congo',
  CI:	'Ivory Coast',
  CK:	'Cook Islands',
  CM:	'Cameroon',
  CP:	'Clipperton Island',
  CV:	'Cape Verde',
  CW:	'Curaçao',
  CX:	'Christmas Island',
  DG:	'Diego Garcia',
  DJ:	'Djibouti',
  DM:	'Dominica',
  EA:	'Ceuta & Melilla',
  EH:	'Western Sahara',
  ER:	'Eritrea',
  ET:	'Ethiopia',
  FJ:	'Fiji',
  FK:	'Falkland Islands',
  FM:	'Micronesia',
  FO:	'Faroe Islands',
  GA:	'Gabon',
  GD:	'Grenada',
  GF:	'French Guiana',
  GG:	'Guernsey',
  GH:	'Ghana',
  GI:	'Gibraltar',
  GL:	'Greenland',
  GM:	'Gambia',
  GN:	'Guinea',
  GP:	'Guadeloupe',
  GQ:	'Equatorial Guinea',
  GS:	'South Georgia & South Sandwich Islands',
  GU:	'Guam',
  GW:	'Guinea-Bissau',
  GY:	'Guyana',
  HM:	'Heard & McDonald Islands',
  HT:	'Haiti',
  IC:	'Canary Islands',
  IO:	'British Indian Ocean Territory',
  JE:	'Jersey',
  KE:	'Kenya',
  KG:	'Kyrgyzstan',
  KH:	'Cambodia',
  KI:	'Kiribati',
  KM:	'Comoros',
  KN:	'St. Kitts & Nevis',
  KO:	'Kosovo',
  KY:	'Cayman Islands',
  LA:	'Laos',
  LC:	'St. Lucia',
  LR:	'Liberia',
  LS:	'Lesotho',
  MF:	'St. Martin',
  MG:	'Madagascar',
  MH:	'Marshall Islands',
  ML:	'Mali',
  MM:	'Myanmar (Burma)',
  MN:	'Mongolia',
  MP:	'Northern Mariana Islands',
  MQ:	'Martinique',
  MR:	'Mauritania',
  MS:	'Montserrat',
  MU:	'Mauritius',
  MV:	'Maldives',
  MW:	'Malawi',
  MZ:	'Mozambique',
  NA:	'Namibia',
  NC:	'New Caledonia',
  NE:	'Niger',
  NF:	'Norfolk Island',
  NI:	'Nicaragua',
  NR:	'Nauru',
  NU:	'Niue',
  PF:	'French Polynesia',
  PG:	'Papua New Guinea',
  PM:	'St. Pierre & Miquelon',
  PN:	'Pitcairn Islands',
  PS:	'Palestinian Territories',
  PW:	'Palau',
  RE:	'Réunion',
  RW:	'Rwanda',
  SB:	'Solomon Islands',
  SC:	'Seychelles',
  SD:	'Sudan',
  SH:	'St. Helena',
  SJ:	'Svalbard & Jan Mayen',
  SL:	'Sierra Leone',
  SN:	'Senegal',
  SR:	'Suriname',
  SS:	'South Sudan',
  ST:	'São Tomé & Príncipe',
  SX:	'Sint Maarten',
  SZ:	'Eswatini',
  TA:	'Tristan da Cunha',
  TC:	'Turks & Caicos Islands',
  TD:	'Chad',
  TF:	'French Southern Territories',
  TG:	'Togo',
  TJ:	'Tajikistan',
  TK:	'Tokelau',
  TL:	'Timor-Leste',
  TO:	'Tonga',
  TV:	'Tuvalu',
  UG:	'Uganda',
  UM:	'U.S. Outlying Islands',
  VA:	'Vatican City',
  VC:	'St. Vincent & Grenadines',
  VG:	'British Virgin Islands',
  VI:	'U.S. Virgin Islands',
  VU:	'Vanuatu',
  WF:	'Wallis & Futuna',
  WS:	'Samoa',
  YE:	'Yemen',
  YT:	'Mayotte',
  ZM:	'Zambia',
  ZW:	'Zimbabwe',
  ENG: 'England',
  SCT: 'Scotland',
  WLS: 'Wales',
  RUI: 'Russian Empire 1858',
};

export { FLAGS_CODE_TO_ISO, COUNTRY_NAMES, FLAGS_ISO_TO_CODE };
